baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'eneoli/notes'
theme = "PaperMod"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]


[params]
math = true
defaultTheme = "dark"

[params.profileMode]
enabled = true
title = "Hi there! 👋"
subtitle = "I'm a computer science student from Germany."
imageUrl = "https://avatars.githubusercontent.com/u/23139864?v=4"
imageTitle = "alt"
imageWidth = 240
imageHeight = 240

[[menu.main]]
name = "Posts"
identifier = "posts"
url = "/posts"

[[params.socialIcons]]
name = ""
icon = "GitHub"
url = "https://github.com/eneoli"

[[params.socialIcons]]
name = "PGP"
icon = "lock"
url = "https://github.com/eneoli.gpg"

[[params.socialIcons]]
name = "eneoli"
icon = "Discord"
url = ""
